// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/consignment/consignment.proto

package go_micro_srv_consignment

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Consignment struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Weight               int32        `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Containers           []*Container `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	VesselId             string       `protobuf:"bytes,5,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{0}
}

func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (m *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(m, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{1}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Wild struct {
	Wild                 string   `protobuf:"bytes,1,opt,name=wild,proto3" json:"wild,omitempty"`
	Usrid                int32    `protobuf:"varint,2,opt,name=usrid,proto3" json:"usrid,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wild) Reset()         { *m = Wild{} }
func (m *Wild) String() string { return proto.CompactTextString(m) }
func (*Wild) ProtoMessage()    {}
func (*Wild) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{2}
}

func (m *Wild) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wild.Unmarshal(m, b)
}
func (m *Wild) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wild.Marshal(b, m, deterministic)
}
func (m *Wild) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wild.Merge(m, src)
}
func (m *Wild) XXX_Size() int {
	return xxx_messageInfo_Wild.Size(m)
}
func (m *Wild) XXX_DiscardUnknown() {
	xxx_messageInfo_Wild.DiscardUnknown(m)
}

var xxx_messageInfo_Wild proto.InternalMessageInfo

func (m *Wild) GetWild() string {
	if m != nil {
		return m.Wild
	}
	return ""
}

func (m *Wild) GetUsrid() int32 {
	if m != nil {
		return m.Usrid
	}
	return 0
}

func (m *Wild) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Amount struct {
	Am                   string   `protobuf:"bytes,1,opt,name=am,proto3" json:"am,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Amount) Reset()         { *m = Amount{} }
func (m *Amount) String() string { return proto.CompactTextString(m) }
func (*Amount) ProtoMessage()    {}
func (*Amount) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{3}
}

func (m *Amount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Amount.Unmarshal(m, b)
}
func (m *Amount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Amount.Marshal(b, m, deterministic)
}
func (m *Amount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Amount.Merge(m, src)
}
func (m *Amount) XXX_Size() int {
	return xxx_messageInfo_Amount.Size(m)
}
func (m *Amount) XXX_DiscardUnknown() {
	xxx_messageInfo_Amount.DiscardUnknown(m)
}

var xxx_messageInfo_Amount proto.InternalMessageInfo

func (m *Amount) GetAm() string {
	if m != nil {
		return m.Am
	}
	return ""
}

type RplAmount struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RplAmount) Reset()         { *m = RplAmount{} }
func (m *RplAmount) String() string { return proto.CompactTextString(m) }
func (*RplAmount) ProtoMessage()    {}
func (*RplAmount) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{4}
}

func (m *RplAmount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RplAmount.Unmarshal(m, b)
}
func (m *RplAmount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RplAmount.Marshal(b, m, deterministic)
}
func (m *RplAmount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RplAmount.Merge(m, src)
}
func (m *RplAmount) XXX_Size() int {
	return xxx_messageInfo_RplAmount.Size(m)
}
func (m *RplAmount) XXX_DiscardUnknown() {
	xxx_messageInfo_RplAmount.DiscardUnknown(m)
}

var xxx_messageInfo_RplAmount proto.InternalMessageInfo

func (m *RplAmount) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{5}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type Response struct {
	Created              bool           `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Consignment          *Consignment   `protobuf:"bytes,2,opt,name=consignment,proto3" json:"consignment,omitempty"`
	Consignments         []*Consignment `protobuf:"bytes,3,rep,name=consignments,proto3" json:"consignments,omitempty"`
	Wild                 string         `protobuf:"bytes,4,opt,name=wild,proto3" json:"wild,omitempty"`
	Lists                []*List        `protobuf:"bytes,5,rep,name=lists,proto3" json:"lists,omitempty"`
	Losstags             []*Tag         `protobuf:"bytes,6,rep,name=losstags,proto3" json:"losstags,omitempty"`
	Proftags             []*Tag         `protobuf:"bytes,7,rep,name=proftags,proto3" json:"proftags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{6}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

func (m *Response) GetConsignments() []*Consignment {
	if m != nil {
		return m.Consignments
	}
	return nil
}

func (m *Response) GetWild() string {
	if m != nil {
		return m.Wild
	}
	return ""
}

func (m *Response) GetLists() []*List {
	if m != nil {
		return m.Lists
	}
	return nil
}

func (m *Response) GetLosstags() []*Tag {
	if m != nil {
		return m.Losstags
	}
	return nil
}

func (m *Response) GetProftags() []*Tag {
	if m != nil {
		return m.Proftags
	}
	return nil
}

type List struct {
	ListId               int32    `protobuf:"varint,1,opt,name=ListId,proto3" json:"ListId,omitempty"`
	Date                 string   `protobuf:"bytes,2,opt,name=Date,proto3" json:"Date,omitempty"`
	Summ                 int32    `protobuf:"varint,3,opt,name=Summ,proto3" json:"Summ,omitempty"`
	Pl                   bool     `protobuf:"varint,4,opt,name=Pl,proto3" json:"Pl,omitempty"`
	UsrId                int32    `protobuf:"varint,5,opt,name=UsrId,proto3" json:"UsrId,omitempty"`
	Tags                 string   `protobuf:"bytes,6,opt,name=Tags,proto3" json:"Tags,omitempty"`
	Set                  string   `protobuf:"bytes,7,opt,name=Set,proto3" json:"Set,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *List) Reset()         { *m = List{} }
func (m *List) String() string { return proto.CompactTextString(m) }
func (*List) ProtoMessage()    {}
func (*List) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{7}
}

func (m *List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_List.Unmarshal(m, b)
}
func (m *List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_List.Marshal(b, m, deterministic)
}
func (m *List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_List.Merge(m, src)
}
func (m *List) XXX_Size() int {
	return xxx_messageInfo_List.Size(m)
}
func (m *List) XXX_DiscardUnknown() {
	xxx_messageInfo_List.DiscardUnknown(m)
}

var xxx_messageInfo_List proto.InternalMessageInfo

func (m *List) GetListId() int32 {
	if m != nil {
		return m.ListId
	}
	return 0
}

func (m *List) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *List) GetSumm() int32 {
	if m != nil {
		return m.Summ
	}
	return 0
}

func (m *List) GetPl() bool {
	if m != nil {
		return m.Pl
	}
	return false
}

func (m *List) GetUsrId() int32 {
	if m != nil {
		return m.UsrId
	}
	return 0
}

func (m *List) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *List) GetSet() string {
	if m != nil {
		return m.Set
	}
	return ""
}

type Tag struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Sort                 int32    `protobuf:"varint,2,opt,name=Sort,proto3" json:"Sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{8}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Tag) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func init() {
	proto.RegisterType((*Consignment)(nil), "go.micro.srv.consignment.Consignment")
	proto.RegisterType((*Container)(nil), "go.micro.srv.consignment.Container")
	proto.RegisterType((*Wild)(nil), "go.micro.srv.consignment.Wild")
	proto.RegisterType((*Amount)(nil), "go.micro.srv.consignment.Amount")
	proto.RegisterType((*RplAmount)(nil), "go.micro.srv.consignment.RplAmount")
	proto.RegisterType((*GetRequest)(nil), "go.micro.srv.consignment.GetRequest")
	proto.RegisterType((*Response)(nil), "go.micro.srv.consignment.Response")
	proto.RegisterType((*List)(nil), "go.micro.srv.consignment.List")
	proto.RegisterType((*Tag)(nil), "go.micro.srv.consignment.Tag")
}

func init() {
	proto.RegisterFile("proto/consignment/consignment.proto", fileDescriptor_e5e5ab05dfa973d5)
}

var fileDescriptor_e5e5ab05dfa973d5 = []byte{
	// 602 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdf, 0x8b, 0xd3, 0x4e,
	0x10, 0xbf, 0xb6, 0x49, 0xdb, 0x4c, 0x8e, 0xef, 0x57, 0x17, 0x39, 0x97, 0x13, 0xb5, 0xec, 0x29,
	0x1c, 0x08, 0x11, 0x4e, 0x5f, 0x7c, 0x94, 0x8a, 0x25, 0xa0, 0x78, 0x6c, 0x2b, 0x3e, 0x89, 0xc6,
	0x64, 0x8d, 0x0b, 0x49, 0xb6, 0xee, 0x6e, 0xee, 0xfe, 0x0f, 0xff, 0x1b, 0xff, 0x2f, 0x1f, 0x7c,
	0x94, 0xfd, 0x91, 0x5e, 0x44, 0x52, 0xfa, 0x94, 0xf9, 0xcc, 0xcc, 0x67, 0x76, 0x32, 0xf3, 0xd9,
	0x85, 0xb3, 0xad, 0x14, 0x5a, 0x3c, 0xcd, 0x45, 0xa3, 0x78, 0xd9, 0xd4, 0xac, 0xd1, 0x7d, 0x3b,
	0xb1, 0x51, 0x84, 0x4b, 0x91, 0xd4, 0x3c, 0x97, 0x22, 0x51, 0xf2, 0x2a, 0xe9, 0xc5, 0xc9, 0xcf,
	0x11, 0xc4, 0xcb, 0x1b, 0x8c, 0xfe, 0x83, 0x31, 0x2f, 0xf0, 0x68, 0x31, 0x3a, 0x8f, 0xe8, 0x98,
	0x17, 0x68, 0x01, 0x71, 0xc1, 0x54, 0x2e, 0xf9, 0x56, 0x73, 0xd1, 0xe0, 0xb1, 0x0d, 0xf4, 0x5d,
	0xe8, 0x04, 0xa6, 0xd7, 0x8c, 0x97, 0xdf, 0x34, 0x9e, 0x2c, 0x46, 0xe7, 0x21, 0xf5, 0x08, 0x2d,
	0x01, 0x72, 0xd1, 0xe8, 0x8c, 0x37, 0x4c, 0x2a, 0x1c, 0x2c, 0x26, 0xe7, 0xf1, 0xc5, 0x59, 0x32,
	0xd4, 0x48, 0xb2, 0xec, 0x72, 0x69, 0x8f, 0x86, 0xee, 0x41, 0x74, 0xc5, 0x94, 0x62, 0xd5, 0x27,
	0x5e, 0xe0, 0xd0, 0x1e, 0x3e, 0x77, 0x8e, 0xb4, 0x20, 0x35, 0x44, 0x3b, 0xd6, 0x3f, 0x8d, 0x3f,
	0x84, 0x38, 0x6f, 0x95, 0x16, 0x35, 0x93, 0x86, 0xeb, 0x1a, 0x87, 0xce, 0x95, 0x16, 0xa6, 0x6f,
	0x21, 0x79, 0xc9, 0x1b, 0xdb, 0x77, 0x44, 0x3d, 0x42, 0x77, 0x61, 0xd6, 0x2a, 0x47, 0x0a, 0x5c,
	0xc0, 0xc0, 0xb4, 0x20, 0xaf, 0x21, 0xf8, 0xc0, 0xab, 0x02, 0x21, 0x08, 0xae, 0x79, 0xd5, 0x9d,
	0x65, 0x6d, 0x74, 0x07, 0xc2, 0x56, 0x49, 0x7f, 0x4e, 0x48, 0x1d, 0x30, 0xde, 0x8a, 0xd7, 0xbc,
	0x9b, 0x8c, 0x03, 0x04, 0xc3, 0xf4, 0x65, 0x2d, 0x5a, 0x37, 0xec, 0xac, 0xee, 0x7a, 0xce, 0x6a,
	0x72, 0x06, 0x11, 0xdd, 0x56, 0x3e, 0x78, 0x02, 0x53, 0xa5, 0x33, 0xdd, 0x2a, 0x9f, 0xe0, 0x11,
	0x39, 0x06, 0x58, 0x31, 0x4d, 0xd9, 0xf7, 0x96, 0x29, 0x4d, 0x7e, 0x8f, 0x61, 0x4e, 0x99, 0xda,
	0x8a, 0x46, 0x31, 0x84, 0x61, 0x96, 0x4b, 0x96, 0x69, 0xe6, 0x9a, 0x9b, 0xd3, 0x0e, 0xa2, 0x15,
	0xc4, 0xbd, 0x61, 0xdb, 0x2e, 0xe3, 0x8b, 0xc7, 0x7b, 0xb7, 0xd1, 0xd9, 0xb4, 0xcf, 0x44, 0x29,
	0x1c, 0xf7, 0xa0, 0xc2, 0x13, 0xbb, 0xd7, 0x03, 0x2b, 0xfd, 0x45, 0xdd, 0xcd, 0x31, 0xe8, 0xcd,
	0xf1, 0xb9, 0x99, 0x98, 0xd2, 0x0a, 0x87, 0xb6, 0xee, 0x83, 0xe1, 0xba, 0x6f, 0xb8, 0xd2, 0xd4,
	0x25, 0xa3, 0x17, 0x30, 0xaf, 0x84, 0x52, 0x3a, 0x2b, 0x15, 0x9e, 0x5a, 0xe2, 0xfd, 0x61, 0xe2,
	0x26, 0x2b, 0xe9, 0x2e, 0xdd, 0x50, 0xb7, 0x52, 0x7c, 0xb5, 0xd4, 0xd9, 0x41, 0xd4, 0x2e, 0x9d,
	0xfc, 0x18, 0x41, 0x60, 0xba, 0x30, 0x9b, 0x32, 0xdf, 0xd4, 0x4d, 0x3d, 0xa4, 0x1e, 0x99, 0x1f,
	0x7c, 0x95, 0x69, 0xe6, 0xb5, 0x67, 0x6d, 0xe3, 0x5b, 0xb7, 0x75, 0xed, 0x15, 0x61, 0x6d, 0x23,
	0x83, 0xcb, 0xca, 0x8e, 0x61, 0x4e, 0xc7, 0x97, 0x95, 0x91, 0xcd, 0x7b, 0x25, 0x53, 0x27, 0xf8,
	0x90, 0x3a, 0x60, 0x98, 0x1b, 0xf7, 0x83, 0xb6, 0x9a, 0xb1, 0xd1, 0x2d, 0x98, 0xac, 0x99, 0xc6,
	0x33, 0xeb, 0x32, 0x26, 0x79, 0x02, 0x93, 0x4d, 0x56, 0x9a, 0xc0, 0x26, 0x2b, 0xbd, 0x72, 0xac,
	0xc7, 0x1c, 0x2c, 0xa4, 0xf6, 0x02, 0xb5, 0xf6, 0xc5, 0xaf, 0x31, 0xc0, 0xdb, 0x46, 0xaf, 0x99,
	0xbc, 0xe2, 0x39, 0x43, 0x9f, 0xe1, 0xf6, 0xd2, 0xea, 0xa5, 0xff, 0x20, 0x1c, 0xb6, 0xda, 0x53,
	0x32, 0x9c, 0xd6, 0xc9, 0x93, 0x1c, 0xa1, 0x8f, 0xf0, 0xff, 0x8a, 0xe9, 0x65, 0x5f, 0x05, 0x8f,
	0x86, 0x89, 0x37, 0x32, 0x3f, 0xb0, 0xfc, 0x3b, 0x98, 0xad, 0x98, 0xb6, 0x97, 0x74, 0x8f, 0x72,
	0x4c, 0xfc, 0xc0, 0x82, 0x1b, 0x88, 0xd6, 0x4c, 0xfb, 0x0b, 0xb9, 0x18, 0xa6, 0xb8, 0x8c, 0xd3,
	0x3d, 0xcf, 0xdb, 0xee, 0x5e, 0x93, 0xa3, 0x2f, 0x53, 0xfb, 0x28, 0x3f, 0xfb, 0x13, 0x00, 0x00,
	0xff, 0xff, 0xef, 0xe3, 0x49, 0x36, 0xbb, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MntServiceClient is the client API for MntService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MntServiceClient interface {
	CreateConsignment(ctx context.Context, in *Consignment, opts ...grpc.CallOption) (*Response, error)
	GetConsignments(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error)
	GetWild(ctx context.Context, in *Wild, opts ...grpc.CallOption) (*Response, error)
	SetAmount(ctx context.Context, in *Amount, opts ...grpc.CallOption) (*RplAmount, error)
}

type mntServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMntServiceClient(cc grpc.ClientConnInterface) MntServiceClient {
	return &mntServiceClient{cc}
}

func (c *mntServiceClient) CreateConsignment(ctx context.Context, in *Consignment, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/go.micro.srv.consignment.MntService/CreateConsignment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mntServiceClient) GetConsignments(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/go.micro.srv.consignment.MntService/GetConsignments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mntServiceClient) GetWild(ctx context.Context, in *Wild, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/go.micro.srv.consignment.MntService/GetWild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mntServiceClient) SetAmount(ctx context.Context, in *Amount, opts ...grpc.CallOption) (*RplAmount, error) {
	out := new(RplAmount)
	err := c.cc.Invoke(ctx, "/go.micro.srv.consignment.MntService/SetAmount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MntServiceServer is the server API for MntService service.
type MntServiceServer interface {
	CreateConsignment(context.Context, *Consignment) (*Response, error)
	GetConsignments(context.Context, *GetRequest) (*Response, error)
	GetWild(context.Context, *Wild) (*Response, error)
	SetAmount(context.Context, *Amount) (*RplAmount, error)
}

// UnimplementedMntServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMntServiceServer struct {
}

func (*UnimplementedMntServiceServer) CreateConsignment(ctx context.Context, req *Consignment) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConsignment not implemented")
}
func (*UnimplementedMntServiceServer) GetConsignments(ctx context.Context, req *GetRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConsignments not implemented")
}
func (*UnimplementedMntServiceServer) GetWild(ctx context.Context, req *Wild) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWild not implemented")
}
func (*UnimplementedMntServiceServer) SetAmount(ctx context.Context, req *Amount) (*RplAmount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAmount not implemented")
}

func RegisterMntServiceServer(s *grpc.Server, srv MntServiceServer) {
	s.RegisterService(&_MntService_serviceDesc, srv)
}

func _MntService_CreateConsignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Consignment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MntServiceServer).CreateConsignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.consignment.MntService/CreateConsignment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MntServiceServer).CreateConsignment(ctx, req.(*Consignment))
	}
	return interceptor(ctx, in, info, handler)
}

func _MntService_GetConsignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MntServiceServer).GetConsignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.consignment.MntService/GetConsignments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MntServiceServer).GetConsignments(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MntService_GetWild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Wild)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MntServiceServer).GetWild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.consignment.MntService/GetWild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MntServiceServer).GetWild(ctx, req.(*Wild))
	}
	return interceptor(ctx, in, info, handler)
}

func _MntService_SetAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Amount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MntServiceServer).SetAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.consignment.MntService/SetAmount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MntServiceServer).SetAmount(ctx, req.(*Amount))
	}
	return interceptor(ctx, in, info, handler)
}

var _MntService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.consignment.MntService",
	HandlerType: (*MntServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConsignment",
			Handler:    _MntService_CreateConsignment_Handler,
		},
		{
			MethodName: "GetConsignments",
			Handler:    _MntService_GetConsignments_Handler,
		},
		{
			MethodName: "GetWild",
			Handler:    _MntService_GetWild_Handler,
		},
		{
			MethodName: "SetAmount",
			Handler:    _MntService_SetAmount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/consignment/consignment.proto",
}
